# Generated by Django 4.2 on 2023-06-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='logo',
            new_name='image',
        ),
    ]
