# Generated by Django 4.2 on 2023-06-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_alter_sneaker_brand_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('Премиум статус', 'Можно покупать все')], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
