# Generated by Django 4.2 on 2023-06-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('base_status', 'Можно покупать все')], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
