# Generated by Django 4.2 on 2023-06-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0005_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='sneaker',
            options={'permissions': [('base_status', 'Можно покупать любые')], 'verbose_name': 'Кроссовки', 'verbose_name_plural': 'Кроссовки'},
        ),
    ]
