# Generated by Django 4.2 on 2023-06-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0006_alter_review_options_alter_sneaker_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sneaker',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
